package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greendao.TABUser;

import greendao.TABUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tABUserDaoConfig;

    private final TABUserDao tABUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tABUserDaoConfig = daoConfigMap.get(TABUserDao.class).clone();
        tABUserDaoConfig.initIdentityScope(type);

        tABUserDao = new TABUserDao(tABUserDaoConfig, this);

        registerDao(TABUser.class, tABUserDao);
    }
    
    public void clear() {
        tABUserDaoConfig.clearIdentityScope();
    }

    public TABUserDao getTABUserDao() {
        return tABUserDao;
    }

}
