package greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TABUSER".
 */
@Entity
public class TABUser {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String age;
    private String passWord;
    private String email;
    private String phoneNumber;
    private String description;

    @Generated
    public TABUser() {
    }

    public TABUser(Long id) {
        this.id = id;
    }

    @Generated
    public TABUser(Long id, String name, String age, String passWord, String email, String phoneNumber, String description) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.passWord = passWord;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getPassWord() {
        return passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
